### ISSUE TITLE
re-close this issue tracker

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#165]
We should re-close this issue tracker once we have finished the last website fixes. I'm opening this now to remind us later :-)

**Comment by roll** [comment]
Or might keep it open for some time till we get to some 1 issue tracker system. I think when it was close it wasn't perfect either

**Comment by roll** [comment]
Agreed with @lwinfree that it will be more manageable for us if we keep this tracker (I think it was the last active repo without an active issue tracker that was creating confusion)
