### ISSUE TITLE
Update the reproducible research page

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#169]
Several updates are needed:
- [x] team members
- [ ] tool fund members
- [x] fellows
- [ ] pilots
- [x] general information

**Comment by lwinfree** [comment]
this is mostly done as it is now part of the adaption page, but we still need to make sure that all the pilots/tool funds are listed

**Comment by roll** [comment]
Then the only this which is outstanding is https://github.com/frictionlessdata/website/issues/170
