### ISSUE TITLE
Add all the pilots/projects/etc to the adoption page

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#170]
Currently, these display blogs that have been tagged as a case study or as a pilot. 

Suggestions for improving these pages:
- [x] The pages could use an intro paragraph
- [x] The articles could be displayed in a nicer format (optional?)
- [x] Add all the projects
- [x] Add all the pilots

Lilly can add the intro paragraph.

Let's chat here about if anyone has ideas for displaying the blogs in a nicer format.

**Comment by lwinfree** [comment]
this is somewhat done, but we still need to add all the pilots etc

**Comment by roll** [comment]
A few project that I think we can add to "Community Projects":
- https://github.com/frictionlessdata/delimiter
- https://github.com/frictionlessdata/schema-collaboration
- ?

**Comment by lwinfree** [comment]
I updated the text about grants and added another pilot. Still To Be Done:

- finish adding all the older pilots
- add a new section for tool funds & add the tool funds

**Comment by lwinfree** [comment]
DONE!
