### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#173]
- [x] Display faces in a non-hierarchical way
- [x] Add new people
- [x] Remove past people (?)
- [ ] Need to add a real contact form or email address

Let's discuss here if we want to display avatars in a similar way to this: https://framework.frictionlessdata.io/docs/development/authors/

**Comment by lwinfree** [comment]
I like the way contributors are displayed like on this page: https://framework.frictionlessdata.io/docs/development/authors/. It feels inclusive to me, and then we don't need to worry about removing past people from the list, because they should still get credit (IMO). What do other people think?

**Comment by lwinfree** [comment]
still need to do this. (just a note for us)

**Comment by roll** [comment]
Current state - https://staging.frictionlessdata.io/people/

@lwinfree 
Do we miss something still? You mentioned a contact form in the first post.

**Comment by lwinfree** [comment]
I think we don't need more contact info here because it is now in the "get help" section. But, the "contact" link in the footer has the wrong url (from when I had put people under the about header).

**Comment by roll** [comment]
Ok. Cool. I'll fix the footer and the redirects
