### ISSUE TITLE
Update blog page

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#174]
- [x] users have asked for an RSS feed (https://github.com/frictionlessdata/project/discussions/603)
- [x] this could be redesigned
- [x] filters

Let's discuss any redesign thoughts/ideas here.

**Comment by lwinfree** [comment]
still need to make filters & do RSS feed

**Comment by roll** [comment]
I thought I had enabled it but it still doesn't work. I'll re-try

**Comment by roll** [comment]
https://staging.frictionlessdata.io/feed.atom

**Comment by roll** [comment]
Added buttons - https://staging.frictionlessdata.io/blog/

**Comment by lwinfree** [comment]
yay!! thanks!
