### ISSUE TITLE
Update content in the Learn section

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#175]
Let's discuss exactly what we need to update. Most of the updates are necessary since the release of Frictionless Framework.

**Overall: we probably need to rearrange some of this content**

### Guide

- Needs a content overhaul
- What is missing?
- What needs to be removed?

### Table Schema

- This is repetitive with info in the guide section
- Make this longer?

### Data Package 

- There are some dead links here
- Check the info that was in those dead links & see if we want to reuse it (should be on github somewhere)
- I have no idea what Views is 😕

**Comment by lwinfree** [comment]
Suggestions from Chris:

- Review which tooling/packages we want to promote/not promote and explain why there is Frictionless Framework but also goodtables/datapackage-py/tableschema-py libs. Explaining this well requires us to have a clear plan for maintenance/deprecation before we can effectively communicate it.
- If I am a new user what do I want/why?
- If I am an existing user of one of the legacy packages, what should I do?
- Explain the ecosystem for other non-python languages.
- The python documentation is now really good, but what about the docs for other language ecosystems. A lot of it is locked up in blog posts which are hard to find. How can we surface it better? ..or perhaps another question is how can we delegate that to ecosystem authors in a good way?

**Comment by lwinfree** [comment]
From @sapetti9:

- Do we need guides here? I find it confusing that we have guides scattered across different websites.
- Explain why Table Schema and Data Package are not up to date and how frictionless.py can be used instead.

**Comment by chris48s** [comment]
As noted by @roll  https://libraries.frictionlessdata.io/ does a pretty good job of collating docs for the non-python ecosystem (although "user projects" is a 404) so that part of the job (docs for other language ecosystems) is probably just linking that up from the main site in a sensible way

**Comment by lwinfree** [comment]
We still need to review this content (mainly the intro). The rest of this issue has been fixed via the software/specs pages

**Comment by roll** [comment]
DONE in https://github.com/frictionlessdata/website/pull/186#issuecomment-849936194
