### ISSUE TITLE
Drop-down menus get stuck sometimes

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#176]
This was an issue before that was resolved, but it seems to be happening again.
<img width="412" alt="Screen Shot 2021-04-21 at 3 07 19 PM" src="https://user-images.githubusercontent.com/17657625/115614456-58f18100-a2b3-11eb-9dcc-194fb3d0f6f9.png">

This doesn't happen for me every time I click on a menu, only sometimes. (I've seen it on Chrome).

**Comment by lwinfree** [comment]
I don't think we've fixed this, but we have removed several drop down options, so it might not be an issue anymore.

**Comment by roll** [comment]
Now we have only 1 drop-down it would be fine :+1:
