### ISSUE TITLE
Make the main site cohesive with the specs site & with the framework docs site

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#178]
Right now we have 3 sites that don't look much a like or aren't linked together well.

- [x] Add links to/from all these sites
- [ ] Update styling on Framework site to match main FD site
- [ ] Update styling on Specs site to match main FD site

**Comment by lwinfree** [comment]
We also need to update the logo/styling on the libraries site (https://libraries.frictionlessdata.io/) & components (https://components.frictionlessdata.io/)

**Comment by roll** [comment]
MERGED into frictionlessdata/frictionlessdata.io#757
