### ISSUE TITLE
Update the staging icons/graphics on website/libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/website#192]
# Overview

Currently, we use some prototypes:
- https://staging.frictionlessdata.io/
- https://libraries.frictionlessdata.io/

**Comment by roll** [comment]
Hi @sapetti9, what do you think are outstanding things to close this one?

**Comment by sapetti9** [comment]
Hey @roll we need a new:
[ ] Fiscal data package icon
[ ] Framework icon
[ ] Table schema icon (with white cells now --ready to be uploaded) 

We need to update the icons with the old logo (they are ready to be uploaded):
[ ] Frictionless Libraries
[ ] Frictionless Repository
[ ] Data Package
+
[ ] Markdown Badges on repository.frictionlessdata.io/

**Comment by roll** [comment]
@sapetti9 
Updated the last parts and moved https://github.com/frictionlessdata/frictionless-py/issues/863 to the framework issues

**Comment by roll** [comment]
I think it's now DONE
