### ISSUE TITLE
Gathering feedback of the ODI-funded website/documentation update

### ISSUE THREAD

**Issue by roll** [frictionlessdata/website#198]
# Overview

As a part of a documentation improvements project funded by ODI, we have created low-level documentation portals and updated the main Frictionless Website in #186.

The list of documentation work done:

> The low-level documentation portals are available on the "Software" page of the main website. Posting links here just for convenience.

- https://frictionlessdata.io/
- ---
- https://framework.frictionlessdata.io/
- https://repository.frictionlessdata.io/
- https://libraries.frictionlessdata.io/
- https://components.frictionlessdata.io/

After these changes, the main website plays a role of a high-level Frictionless Data overview and "landing page" while low-level documentation portals are meant for technical users and contributors and contain a great deal of low-level technical documentation.

We are looking forward to hearing from Frictionless Core Team and Community. What do you think? Is it getting better structured and easier to understand? Please share your thoughts.

**Comment by amercader** [comment]
Well done team on the changes, overall I think the information is much better structured.

This feedback is mostly related to the mobile experience. I don't know if this is a result of the current changes or it was already an issue before but in any case I think this should be on the backlog.

While mobile Chrome seems to render the mobile optimized design, Firefox mobile just renders the desktop site, which of course doesn't look great and is hard to navigate:

![Screenshot_20210615-212919](https://user-images.githubusercontent.com/200230/122371901-8760a500-cf60-11eb-9d96-ed005449e910.png)
----

While the site renders fine in Chrome, the images don't look properly sized:

![Screenshot_20210617-114536](https://user-images.githubusercontent.com/200230/122373183-9431c880-cf61-11eb-906e-14e028ecc174.png)

**Comment by lwinfree** [comment]
thanks @amercader! noting that I have the same issues on mobile safari.

**Comment by roll** [comment]
Hi @sglavoie,

I wanted to check with you if it's only me or not. When I go to https://datahub.io/ I see:

![datahub](https://user-images.githubusercontent.com/557395/123120209-6a3a4380-d444-11eb-9c79-9487f24f1d7c.png)

where "By" seems to be broken.

**Comment by sglavoie** [comment]
@roll you are absolutely right: the URL of that image is incorrect, I'll flag that on our end. At this time, the website is [not rebuilding successfully](https://github.com/datopian/frontend/runs/2891626826), but I will let you know once we have updates. :slightly_smiling_face:

**Comment by lwinfree** [comment]
hi @roll I'm going to close this now as I think we've successfully gathered & implemented feedback.
