### ISSUE TITLE
Long shot idea: moving toolfund/fellow to the main website

### ISSUE THREAD

**Issue by roll** [frictionlessdata/website#207]
# Overview

It's a long shot but I think it might have sense to merge contents of `toolfund` (as a summary paragraph on the adoption page) and `fellows` (as `Fellowship` top navbar item) to the main website.

Reasons:
- I think it's been hidden from the general public because it's basically invisible from the main site and uses a subdomain. TBH for myself I didn't know that something was happening on the `fellows`. And I'm not really new to the project =)
- They are two additional websites to style/logo/etc. Having separate subsites makes sense for low-lever tech docs generated from the codebase repositories but for content-only user-facing I think it might be an overkill. It's easier to manage it on the main website.

Reasons summary: increase their visibility to the general public

**Comment by lwinfree** [comment]
this is on my list to think about in the next few months, so I don't yet have a solid opinion. But, right now here are my thoughts:
- I think it makes sense to get rid of the tool fund site & incorporate it into the main site (tbh most of the info is already on the main site)
- the fellows site is a teaching website - it is like their sandbox/playground where they can safely practice using github to upload blogs. They also use it for their syllabus. So, right now, I would say that it should remain separate. But, let me think about it some more.

**Comment by roll** [comment]
We're doing it partially it here - https://github.com/frictionlessdata/frictionlessdata.io/issues/758
