### ISSUE TITLE
nav bar menu options overlap

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#40]
Hi all, when one clicks on several options in the nav bar, their drop down menu options overlap:
<img width="361" alt="Screen Shot 2020-03-02 at 3 51 16 PM" src="https://user-images.githubusercontent.com/17657625/75721348-d74d2700-5c9d-11ea-94ec-c3beff6e8688.png">

**Comment by lauragift21** [comment]
Issue also documented here. https://github.com/frictionlessdata/project/issues/439

**Comment by rufuspollock** [comment]
DUPLICATE (and FIXED). https://github.com/frictionlessdata/project/issues/439
