### ISSUE TITLE
reproducible research page is missing

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#42]
https://frictionlessdata.io/reproducible-research/

**Comment by lauragift21** [comment]
This is the page you are talking about right? https://next.frictionlessdata.io/reproducible-research

**Comment by lwinfree** [comment]
Hi @lauragift21 yes, thanks! I couldn't find it. I looks like it isn't linked anywhere - not in the nav bar or any other menu. It also looks like it needs to be styled (and maybe edited a little).

**Comment by lauragift21** [comment]
We've added a link to it in the new landing page mockup.

**Comment by lwinfree** [comment]
Awesome, thanks @lauragift21 !

**Comment by roll** [comment]
FIXED 

https://frictionlessdata.io/reproducible-research/

**Comment by lwinfree** [comment]
Hey @lauragift21 I can't find the link to this page still. Is it possible to add a link to the nav bar? Thanks!
