### ISSUE TITLE
[Vssue]Joining the Frictionless Data Team

### ISSUE THREAD

**Issue by lauragift21** [frictionlessdata/website#65]
https://frictionlessdata.io/blog/2020/03/20/joining-the-frictionless-data-team/

**Comment by roll** [comment]
Hi, I'm curious why it asks for reading/writing permissions for all public repositories

**Comment by lauragift21** [comment]
Hi @roll. It's probably how I set up the OAuth app. I can change this to only have access to Issues.

**Comment by roll** [comment]
Hi @lauragift21 I think it's really important to make it minimal. Just my personal experience - I decided to click decline when I'd seen what it had asked

**Comment by lauragift21** [comment]
Alright, thanks for that feedback. I'll change the access rights.

**Comment by lauragift21** [comment]
@roll I tried changing the access right but I was unable to it appears the scope is set by default from the Vssue plugin to `public_repo`.

**Comment by roll** [comment]
Weird, probably it's a Github not-enough-granular permissions problem
