### ISSUE TITLE
Not listed as tool fund partner

### ISSUE THREAD

**Issue by kleanthisk10** [frictionlessdata/website#73]
Hello! 

I have been involved with the implementation of data package and table schema libraries for R language, on behalf of okfn greece, but not listed as tool fund partner here: https://frictionlessdata.io/team/#tool-fund-partners

Related announcements:
- https://frictionlessdata.io/blog/2017/10/27/open-knowledge-greece/
- https://blog.okfn.org/2017/07/03/frictionless-data-introducing-our-tool-fund-grantees/

**Comment by lauragift21** [comment]
Hi @kleanthisk10. we apologize as we might have missed yours while updating the website. Happy to help fix that. Can you share your location, profile image, and projects?

**Comment by rufuspollock** [comment]
@lauragift21 we could even show @kleanthisk10 the file to edit so he can do a PR - that way he is empowered and others in future can "self-serve" too 😄

**Comment by lauragift21** [comment]
Sure! @rufuspollock 

@kleanthisk10 You can add your details to this file and send in a PR. https://github.com/frictionlessdata/website/blob/master/site/team/index.md

**Comment by kleanthisk10** [comment]
Is there any sorting rule (e.g. by name, language, year, etc)?

**Comment by lauragift21** [comment]
@kleanthisk10 Right now I don't think there is one. But in the future, it'll most likely be sorted by year.

**Comment by lauragift21** [comment]
This is now resolved. I'll be closing this issue.
