### ISSUE TITLE
list of blog authors to be fixed

### ISSUE THREAD

**Issue by lwinfree** [frictionlessdata/website#78]
Hi @lauragift21! [Here's a list](https://docs.google.com/spreadsheets/d/1FwdSjjHDW3GppqzaFIzw_b_EmoQiqCaMHYy4f6B8Wi0/edit#gid=0) of all the blogs noting where the author needs to be changed.
Also, for the case studies, they all have "interviewees" but this information isn't being shown (it is present in the metadata). Can it be shown?

Thanks!

**Comment by lauragift21** [comment]
Sure I'll have a look and implement that.
